server:
  port: 8090

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/db_inventory
    username: master
    password: Ll04QxU9wbizyuZ8T9dD

application:
  request:
    mappings: /app-jwt-auth
    origin: http://localhost:4200/
  secret:
    jwt-secret: 86113AA658B5A70D1D10F5305EAB9CE8675B2C9FACDF7D6910E87596132A94ED

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
